#### 26강 ~ 인덱싱은 아마 다차원 배열이해를 위해 면밀하게 설명하신듯, pass!

##### 하지만 열 인덱싱은 다시 짚고 넘어간다.

In [1]:
import numpy as np

In [4]:
arr = np.arange(0, 35).reshape(-1,7)
arr

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

##### 간단~

In [6]:
arr[:,2]

array([ 2,  9, 16, 23, 30])

##### 이렇게 하는 것이 좀 더 그럴듯하다

In [11]:
arr[:,2].reshape(5,-1)

array([[ 2],
       [ 9],
       [16],
       [23],
       [30]])

##### 일부러 달력처럼 그린 이유

In [15]:
arr[:,:3]

array([[ 0,  1,  2],
       [ 7,  8,  9],
       [14, 15, 16],
       [21, 22, 23],
       [28, 29, 30]])

##### 지옥 달력

In [17]:
arr[:,1:6]

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12],
       [15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26],
       [29, 30, 31, 32, 33]])

#### 간혹 인덱싱이 아닌 마스크로 하는게 더 나을 때가 있을 수도?

### 32강 뷰가있다?

###### 그냥 인덱싱...같은데

In [19]:
view = arr[:,1:6]
view

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12],
       [15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26],
       [29, 30, 31, 32, 33]])

In [20]:
arr[4][4] = 777

##### 이렇게 값이 변한다는 것만 기억하자

In [21]:
view

array([[  1,   2,   3,   4,   5],
       [  8,   9,  10,  11,  12],
       [ 15,  16,  17,  18,  19],
       [ 22,  23,  24,  25,  26],
       [ 29,  30,  31, 777,  33]])

### 33강 넘파이 고유인덱싱 방식

In [23]:
view = arr[1, 1:]
view

array([ 8,  9, 10, 11, 12, 13])

In [24]:
view = arr[1][1:]
view

array([ 8,  9, 10, 11, 12, 13])

In [25]:
py_list = [[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]]

#### 파이썬 기본 문법에서 이게 안된다는 거만 기억하면 끝

In [26]:
py_view = py_list[1, 1:]
py_view

TypeError: list indices must be integers or slices, not tuple

In [27]:
py_view = py_list[1][1:]
py_view

[8, 9, 10, 11, 12, 13]

### 35강 ~ 36강 짝(홀) 인덱싱

##### 반복문 안쓰기 위해.

##### 일단 스텝이라고생각하면 편함

In [28]:
arr[::2]

array([[  0,   1,   2,   3,   4,   5,   6],
       [ 14,  15,  16,  17,  18,  19,  20],
       [ 28,  29,  30,  31, 777,  33,  34]])

In [29]:
arr[2::]

array([[ 14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 28,  29,  30,  31, 777,  33,  34]])

In [31]:
arr[::6]

array([[0, 1, 2, 3, 4, 5, 6]])

In [34]:
arr[::545514848415] # 그 이상은 무조건 첫 행인가

array([[0, 1, 2, 3, 4, 5, 6]])

##### 이러면 안나오긴 하겠지. 하지만 shape가 유지된다는 게 신기할 따름

In [35]:
arr[545514848415::] 

array([], shape=(0, 7), dtype=int64)

### 38강 보드캐스팅(1)

In [37]:
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([1,2,3])

##### 단순계산

In [38]:
arr_1 + 4

array([5, 6, 7, 8, 9])

##### 짠 에러~

In [39]:
arr_1 + arr_2

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

##### 한 짝이 맞으면 되나보네

In [40]:
arr_1 = np.ones((4,4))
arr_2 = np.arange(4)

In [44]:
arr_2

array([0, 1, 2, 3])

In [43]:
arr_1 + arr_2

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

##### 아, 고등학생때 배운거구나

In [45]:
np.dot(arr_1, arr_2)

array([6., 6., 6., 6.])

In [49]:
arr_1 = np.arange(5).reshape(5,1)
arr_2 = np.arange(5)

In [50]:
arr_1

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [51]:
arr_1 + arr_2

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

##### 이경우 하나도 안맞는거지

In [52]:
np.dot(arr_1, arr_2)

ValueError: shapes (5,1) and (5,) not aligned: 1 (dim 1) != 5 (dim 0)

#### 에러 나지 않나?

In [53]:
arr_1 = np.arange(5).reshape(5,1)
arr_2 = np.arange(3)

In [54]:
arr_1 + arr_2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

#### 아... 더할 때는 shape가 확장된다고 가정하면 쉽다

In [56]:
arr_2 + arr_1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### 정리하면

- 스칼라 값과 연산은 브로드캐스팅 가능.
- 차원이 같거나 어느 한쪽의 배열크기가 1인경우(행, 열) 브로드캐스팅 가능
- 차원에 대해 축(axis)의 길이가 동일하다면 브로드 캐스팅 가능

In [65]:
arr_1 = np.arange(27).reshape(3,3,3)
arr_2 = np.arange(9).reshape(3,3)

In [66]:
arr_1 + arr_2

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]],

       [[18, 20, 22],
        [24, 26, 28],
        [30, 32, 34]]])

### 44강 비교 연산도 된다

In [67]:
arr_1 = np.arange(5).reshape(5,1)
arr_2 = np.arange(5)

##### 차원이 늘어난다는 것은 같다. 당연 브로드캐스팅이 가능한 관계에서만 가능

In [68]:
arr_1 == arr_2

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])