# 예전에 그냥 지나쳤던 것들만 복습

In [1]:
import numpy as np

## 11강 단위행렬

##### "단위행렬"이라고는 하지만 어디에 쓰는지 모르는...

In [2]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 12강 행렬 곱셈

##### 행렬 곱셈 : 트랜스포머에서 KVQ 이해할때 이 개념이 필요할 것 같다

In [4]:
arr_1 = np.eye(2)
arr_2 = np.array([[3,4],[5,6]])

##### 단순 곱셈하면 같은 위치의 숫자만 나옴

In [5]:
arr_1 * arr_2

array([[3., 0.],
       [0., 6.]])

##### 진짜 곱셈은 dot메소드

In [13]:
np.dot(arr_1, arr_2)

array([[3., 4.],
       [5., 6.]])

##  15 ~ 16 강 {단원명 못생김}

#### 지금껏 tf와 torch가 알아서 해줬던...

In [15]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
arr.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [22]:
arr.reshape(-9999,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

##### 아 -n 은 조커다🤣🤣, 근데 나는 그냥 계산기를 두들기거나 소인수분해부터 할 것 같긴해

In [23]:
arr.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### 뒤집!

In [24]:
arr.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

###### 특별한거 없어서 여기서부터 흥미 떨어짐

In [25]:
arr.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 19 자료형

##### 사실 딥러닝에서는 타입이 고정되어 있지만, 딥러닝 말고 다른 곳에 사용할 곳이 많을 것

In [27]:
arr = np.array([0,1,2,3,-1], dtype=np.int16)
arr

array([ 0,  1,  2,  3, -1], dtype=int16)

##### 아 워닝 메시지 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

In [28]:
arr = np.array([0,1,2,3,-1], dtype=np.uint16)
arr
###

/tmp/ipykernel_3566/1249274604.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint16 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr = np.array([0,1,2,3,-1], dtype=np.uint16)


array([    0,     1,     2,     3, 65535], dtype=uint16)

##### 0만 False

In [29]:
arr = np.array([0,1,2,3,-1], dtype=np.bool_)
arr
###

array([False,  True,  True,  True,  True])

## 21강 언더바("_")

In [31]:
arr = np.int_([1,2,3,4,5])
arr.dtype

dtype('int64')

##### numpy가 업데이트 되면서 사라

In [34]:
arr = np.int([1,2,3,4,5]) # <<< 여기서 펑
arr.dtype

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [36]:
item = np.int(2) # <<< 이것도 펑!

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [37]:
f = np.float_(0.1)
f = np.float(0.1) # <<<< 펑!

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

## 22강 빅엔디언 vs 리틀엔디언 

###### https://softtone-someday.tistory.com/20
#### 네트워크에서는 빅엔디안
#### 넘파이에서는 리틀엔디안

In [48]:
arr_little = np.array([1,2,3,4], dtype='<u1')
arr_big = np.array([1,2,3,4], dtype='>u1')

In [49]:
arr_little

array([1, 2, 3, 4], dtype=uint8)

In [50]:
arr_big

array([1, 2, 3, 4], dtype=uint8)

##### 이러면 알 수는 있다만... 어?

In [51]:
print(arr_little.dtype.byteorder)
print(arr_big.dtype.byteorder)
print(arr_little[1].dtype.byteorder)
print(arr_big[1].dtype.byteorder)

|
|
|
|


##### 이걸 발견했으니

In [52]:
dt = np.dtype('>i4')
dt.byteorder

'>'

In [54]:
arr_little = np.array([1,2,3,4], dtype=np.dtype('<u1'))
arr_big = np.array([1,2,3,4], dtype=np.dtype('>u1'))

###### 안됨...

In [55]:
print(arr_little.dtype.byteorder)
print(arr_big.dtype.byteorder)
print(arr_little[1].dtype.byteorder)
print(arr_big[1].dtype.byteorder)

|
|
|
|


### 아 드디어👍

In [61]:
arr_little = np.array([1,2,3,4], dtype=np.dtype('<i4'))
arr_big = np.array([1,2,3,4], dtype=np.dtype('>i4'))

In [62]:
print(arr_little.dtype.byteorder)
print(arr_big.dtype.byteorder)
print(arr_little[1].dtype.byteorder)
print(arr_big[1].dtype.byteorder)

=
>
=
=


#### 하긴 Fortran 방식으로 하는 것도 있으니 생각해보면 넘파이는 여러군데 에서 사용 될듯

## 23강 issubtype()

###### https://numpy.org/doc/stable/reference/generated/numpy.issubdtype.html

#### ~키야~~~~

In [64]:
ints = np.array([1, 2, 3], dtype=np.int32)
print(np.issubdtype(ints.dtype, np.integer))
print(np.issubdtype(ints.dtype, np.int32))
print(np.issubdtype(ints.dtype, np.int64))

True
True
False


###### 하지만 난 쓸일이 없었겠지... 아마 다른 라이브러리가 알아서 다 해주고 있었을 듯...